apiVersion: v1
data:
  accounts.image-updater: apiKey
  accounts.image-updater.enabled: "true"
  dex.config: |
    connectors:
      # GitHub example
      - type: github
        id: github
        name: GitHub
        config:
          clientID: ClientID_Of_GitHub
          clientSecret: $argocd-secret:dex.github.clientSecret # Alternatively $<some_K8S_secret>:dex.github.clientSecret
          orgs:
          - name: orgname
  url: http://redirectback.url.of.argo.domain/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd