apiVersion: v1
data:
  policy.csv: |
    p, role:readonly, applications, get, */*, allow
    p, role:readonly, certificates, get, *, allow
    p, role:readonly, clusters, get, *, allow
    p, role:readonly, repositories, get, *, allow
    p, role:readonly, projects, get, *, allow
    p, role:readonly, accounts, get, *, allow
    p, role:readonly, gpgkeys, get, *, allow

    p, role:admin, applications, create, */*, allow
    p, role:admin, applications, update, */*, allow
    p, role:admin, applications, delete, */*, allow
    p, role:admin, applications, sync, */*, allow
    p, role:admin, applications, override, */*, allow
    p, role:admin, applications, action/*, */*, allow
    p, role:admin, certificates, create, *, allow
    p, role:admin, certificates, update, *, allow
    p, role:admin, certificates, delete, *, allow
    p, role:admin, clusters, create, *, allow
    p, role:admin, clusters, update, *, allow
    p, role:admin, clusters, delete, *, allow
    p, role:admin, repositories, create, *, allow
    p, role:admin, repositories, update, *, allow
    p, role:admin, repositories, delete, *, allow
    p, role:admin, projects, create, *, allow
    p, role:admin, projects, update, *, allow
    p, role:admin, projects, delete, *, allow
    p, role:admin, accounts, update, *, allow
    p, role:admin, gpgkeys, create, *, allow
    p, role:admin, gpgkeys, delete, *, allow

    p, role:company-admin, applications, *, */*, allow
    p, role:company-admin, projects, create, *, allow
    p, role:company-admin, projects, update, *, allow
    p, role:company-admin, projects, delete, *, allow
    p, role:company-admin, clusters, get, *, allow
    p, role:company-admin, repositories, get, *, allow
    p, role:company-admin, repositories, create, *, allow
    p, role:company-admin, repositories, update, *, allow
    p, role:company-admin, repositories, delete, *, allow
    p, role:company-admin, logs, get, *, allow
    p, role:company-admin, exec, create, */*, allow

    p, role:image-updater, applications, *, */*, allow
    p, role:image-updater, projects, *, */*, allow
    p, role:image-updater, clusters, *, */*, allow
    p, role:image-updater, repositories, *, */*, allow
    p, role:image-updater, logs, *, */*, allow
    p, role:image-updater, exec, *, */*, allow
    p, role:image-updater, gpgkeys, create, *, allow
    p, role:image-updater, certificates, create, *, allow
    g, image-updater, role:image-updater

    g, company:argorbac, role:company-admin
    g, jamal.shahverdiyev@company.com, role:company-admin
  policy.default: role:readonly
  scopes: '[groups, email]'
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-rbac-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-rbac-cm
  namespace: argocd