apiVersion: v1
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: Company Google Container Registry
      api_url: https://gcr.io
      credentials: pullsecret:argocd/gcr-json-key
      ping: yes
      prefix: gcr.io
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-ssh-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-ssh-config
  namespace: argocd