apiVersion: v1
data:
  accounts.image-updater: apiKey
  accounts.image-updater.enabled: "true"
  dex.config: |
    connectors:
    - config:
        issuer: https://accounts.google.com
        clientID: service-account-of.apps.googleusercontent.com
        clientSecret: client-secret-of.google.cloud
      type: oidc
      id: google
      name: Google
  url: https://url.redirect.back.to.coorporate.domain/
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-cm
    app.kubernetes.io/part-of: argocd
  name: argocd-cm
  namespace: argocd