apiVersion: v1
data:
  log.level: debug
  registries.conf: |
    registries:
    - name: Company Google Container Registry
      api_url: https://gcr.io
      credentials: pullsecret:argocd/gcr-json-key
      ping: yes
      prefix: gcr.io
    - name: Company Artifact Registry
      api_url: https://us-central1-docker.pkg.dev
      credentials: pullsecret:argocd/artifact-registry-key
      ping: yes
      prefix: us-central1-docker.pkg.dev
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name: argocd-image-updater-config
    app.kubernetes.io/part-of: argocd-image-updater
  name: argocd-image-updater-config
  namespace: argocd