apiVersion: batch/v1
kind: CronJob
metadata:
  name: argocleaner
  namespace: default
spec:
  schedule: "* * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: argocleaner
            image: container.registry.domain/with/path/:containerversion
            envFrom:
            - secretRef:
                name: argocleaner
          restartPolicy: OnFailure